notifications: false
targets:
  centos-6:
    dependencies:
      - nginx
      - postgresql-server
  centos-7:
    dependencies:
      - nginx
      - postgresql-server
  debian-8:
    dependencies:
      - nginx
      - postgresql
  ubuntu-16.04:
    dependencies:
      - nginx
      - postgresql
  sles-12:
    dependencies:
      - nginx
      - postgresql-server
before:
  - uname -a
  - ruby -v
  - env
  - echo "gem 'mysql2'" >> Gemfile.local
  - "cat Gemfile.lock"
  - contrib/cleanup.sh
env:
  - RAILS_ENV=production
  - PORT=3000
services:
  - postgres
after_install: contrib/packager.io/postinstall.sh
