---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-deployment
  labels:
    app: zammad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zammad
  template:
    metadata:
      labels:
        app: zammad
    spec:
      containers:
      - name: zammad
        image: zammadjoel.azurecr.io/zammad:bf8506639d3b5067b8b9ca407bb395eb8208228a
        ports:
        - containerPort: 80