workflow:
  rules:
    # Avoid duplicate branch and MR pipelines for push events.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always