name: docker-release

on:
  push:
    branches:
      - stable
      - develop
      - develop-**
    tags:
      - '*'

jobs:
  docker-build-arm64:
    # runs-on: ubuntu-22.04
    runs-on: ['self-hosted', 'arm64']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Get version tag in the old way
        run: echo ZAMMAD_VERSION="$(git describe --tags | sed -e 's/-[a-z0-9]\{8,\}.*//g')" >> $GITHUB_ENV

      - name: Docker metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          # images: |
          #   ghcr.io/${{ github.repository_owner }}/zammad
          #   index.docker.io/${{ github.repository_owner }}/zammad
          #   index.docker.io/${{ github.repository_owner }}/zammad-docker-compose
          #   quay.io/${{ github.repository_owner }}/zammad
          images: |
            index.docker.io/${{ github.repository_owner }}/zammad-multiarch-test

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          outputs: type=image,name=zammad/zammad-multiarch-test,push-by-digest=true,name-canonical=true,push=true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Export digest
        run: |
          mkdir -p tmp/docker-digests
          digest="${{ steps.docker_build.outputs.digest }}"
          touch "tmp/docker-digests/${digest#sha256:}"
          ls -lah tmp/docker-digests/*

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: "docker-digests"
          path: tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  docker-multiarch-manifest:
    runs-on: ubuntu-22.04
    # runs-on: ['self-hosted', 'arm64']
    needs:
      - docker-build-arm64
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: "docker-digests"
          path: tmp/digests

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Get version tag in the old way
        run: echo ZAMMAD_VERSION="$(git describe --tags | sed -e 's/-[a-z0-9]\{8,\}.*//g')" >> $GITHUB_ENV

      - name: Docker metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          # images: |
          #   ghcr.io/${{ github.repository_owner }}/zammad
          #   index.docker.io/${{ github.repository_owner }}/zammad
          #   index.docker.io/${{ github.repository_owner }}/zammad-docker-compose
          #   quay.io/${{ github.repository_owner }}/zammad
          images: |
            index.docker.io/${{ github.repository_owner }}/zammad-multiarch-test
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'stable') }}
            type=raw,value=${{ env.ZAMMAD_VERSION }},enable=${{ github.ref == format('refs/heads/{0}', 'stable') }}
            type=raw,value=zammad-${{ env.ZAMMAD_VERSION }},enable=${{ github.ref == format('refs/heads/{0}', 'stable') }}
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha

      - name: Create manifest list and push
        working-directory: tmp/digests
        run: |
          ls -lah tmp/digests/*
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") $(printf 'zammad/zammad-multiarch-test@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect zammad/zammad-multiarch-test:${{ steps.meta.outputs.version }}